proto:
  max_workers: 2
  address: "localhost:51021"

device_info:
  device_id: "qulacs"
  provider_id: "oqtopus"
  max_qubits: 16
  max_shots: 10000

# Plugin configuration
plugin:
  name: "qulacs" # Available options: "qulacs", "qubex"
  backend:
    module_path: "device_gateway.plugins.qulacs.backend"
    class_name: "QulacsBackend"

# Qubex plugin configuration. Uncomment to use Qubex backend
# plugin:
#   name: "qubex" # Available options: "qulacs", "qubex"
#   backend:
#     module_path: "device_gateway.plugins.qubex.backend"
#     class_name: "QubexBackend"

# Common backend settings
device_status_path: config/gateway/device_status
device_topology_json_path: config/gateway/device_topology_sim.json
